// 引入 Dockerfile 表单 schema，字段、默认值和选项从这里读取。
import schema from "./dockerfile/schema.json";
import reference from "./dockerfile/reference-doc.json";
// 引入 schema 加载器，把 JSON 数据转换成响应式表单状态。
import { applyStateFromSchema, createSchemaForm } from "./loader";
// 引入共享工具函数，负责数字兜底、字符串清理和多行解析。
import { asNumber, cleanString, parseKeyValuePairs, parseLines } from "./shared";

// 用户可能只填参数，也可能填完整指令；这里保证输出始终是合法 Dockerfile 指令。
function renderInstruction(keyword, value) {
  const line = cleanString(value);
  if (!line) {
    return "";
  }

  return line.toUpperCase().startsWith(`${keyword} `) ? line : `${keyword} ${line}`;
}

// ENV 输入沿用通用键值对格式，换行和逗号都允许作为分隔符。
function parseEnvPairs(value) {
  return parseKeyValuePairs(String(value || "").replace(/\n/g, ","));
}

// 把解析后的环境变量转成多行 ENV，避免手写字符串时遗漏前缀。
function renderEnvLines(envPairs) {
  return envPairs.map(([key, value]) => `ENV ${key}=${value}`);
}

// 创建 Dockerfile 参考配置生成器。
export function createDockerfileGenerator() {
  // Dockerfile 先作为 JSON schema 驱动试点：数据外置，生成逻辑仍保留在本模块。
  const { state, groups } = createSchemaForm(schema);

  // 根据运行阶段类型返回最终 runtime 镜像。
  function runtimeImage() {
    // Caddy 模式使用 caddyImage，否则默认使用 nginxImage。
    return state.runtime === "caddy" ? cleanString(state.caddyImage) : cleanString(state.nginxImage);
  }

  // 根据运行阶段类型返回静态文件复制目标目录。
  function runtimeCopyTarget() {
    // Caddy 官方镜像默认静态根目录是 /usr/share/caddy。
    return state.runtime === "caddy" ? "/usr/share/caddy" : "/usr/share/nginx/html";
  }

  // 根据当前表单状态生成 Dockerfile 文本。
  function generateConfig() {
    // 清理工作目录输入，并在用户清空时回退到 /app。
    const appDir = cleanString(state.appDir) || "/app";
    // 清理构建产物目录输入，并在用户清空时回退到 dist。
    const outputDir = cleanString(state.outputDir) || "dist";
    const envPairs = parseEnvPairs(state.envVars);
    const extraCopyInstructions = parseLines(state.extraCopyInstructions);
    const extraRunInstructions = parseLines(state.extraRunInstructions);
    const entrypointInstruction = renderInstruction("ENTRYPOINT", state.entrypointInstruction);
    const cmdInstruction = renderInstruction("CMD", state.cmdInstruction);
    // lines 是最终 Dockerfile 的逐行内容。
    const lines = [
      // 标记配置来源。
      "# Generated by Config Gen",
      // 构建阶段基础镜像。
      `FROM node:${cleanString(state.nodeVersion)} AS builder`,
      // 空行分隔基础镜像和工作目录。
      "",
      // 工作目录注释。
      "# 设置容器内工作目录。",
      // 设置容器内工作目录。
      `WORKDIR ${appDir}`,
      // 空行分隔工作目录和依赖处理。
      "",
    ];

    if (envPairs.length) {
      lines.push(
        "# 写入构建和运行阶段都可见的环境变量。",
        ...renderEnvLines(envPairs),
        "",
      );
    }

    // pnpm/yarn 场景如果开启 Corepack，则输出 corepack enable。
    if (state.enableCorepack && state.packageManager !== "npm") {
      // Corepack 帮助目标项目使用 packageManager 声明的包管理器版本。
      lines.push("# 启用 Corepack，便于使用 pnpm/yarn 的锁定版本。", "RUN corepack enable", "");
    }

    // 先复制依赖清单，提升 Docker layer cache 命中率。
    lines.push(
      // 说明为什么先复制 package 文件。
      "# 先复制依赖清单，利用 Docker layer cache 加快后续构建。",
      // npm 场景复制 package.json 和 package-lock.json。
      "COPY package*.json ./",
    );

    // pnpm 项目需要额外复制 pnpm-lock.yaml。
    if (state.packageManager === "pnpm") {
      // 使用通配符允许没有锁文件时仍作为参考模板。
      lines.push("COPY pnpm-lock.yaml* ./");
    }
    // yarn 项目需要额外复制 yarn.lock。
    if (state.packageManager === "yarn") {
      // 使用通配符允许没有锁文件时仍作为参考模板。
      lines.push("COPY yarn.lock* ./");
    }

    // 输出安装依赖、复制源码和构建产物的核心步骤。
    lines.push(
      // 空行分隔依赖清单复制和安装命令。
      "",
      // 安装依赖注释。
      "# 安装依赖。",
      // 用户配置的安装命令。
      `RUN ${cleanString(state.installCommand)}`,
      // 空行分隔安装和构建。
      "",
      // 构建阶段注释。
      "# 复制源代码并执行构建。",
      // 复制目标项目源码到镜像。
      "COPY . .",
    );

    if (extraCopyInstructions.length) {
      lines.push(
        "",
        "# 额外复制目标项目文件或目录。",
        ...extraCopyInstructions.map((line) => renderInstruction("COPY", line)),
      );
    }

    lines.push(
      // 执行用户配置的构建命令。
      `RUN ${cleanString(state.buildCommand)}`,
    );

    if (extraRunInstructions.length) {
      lines.push(
        "",
        "# 额外构建命令，适合生成类型文件、预处理资源或执行校验。",
        ...extraRunInstructions.map((line) => renderInstruction("RUN", line)),
      );
    }

    lines.push("");

    // 多阶段构建模式会生成独立运行镜像。
    if (state.enableMultiStage) {
      // 输出运行阶段镜像和静态产物复制步骤。
      lines.push(
        // 运行阶段说明。
        "# 运行阶段只保留静态产物。",
        // 运行阶段基础镜像。
        `FROM ${runtimeImage()} AS runtime`,
        // 空行分隔运行镜像和复制步骤。
        "",
      );

      if (envPairs.length) {
        lines.push(
          "# 写入运行阶段环境变量。",
          ...renderEnvLines(envPairs),
          "",
        );
      }

      lines.push(
        // 复制静态产物说明。
        "# 复制构建产物到静态 Web 根目录。",
        // 从 builder stage 复制构建产物到运行镜像的 Web 根目录。
        `COPY --from=builder ${appDir}/${outputDir} ${runtimeCopyTarget()}`,
        // 空行分隔复制步骤和端口声明。
        "",
        // 端口声明说明。
        "# 声明容器对外服务端口。",
        // Dockerfile EXPOSE 是声明用途，不会自动发布宿主机端口。
        `EXPOSE ${asNumber(state.exposePort, 80)}`,
      );
    } else {
      // 单阶段模式保留 Node 镜像，并使用 serve 提供静态文件。
      lines.push(
        // 单阶段运行说明。
        "# 单阶段运行参考：直接在 Node 镜像内用 serve 提供静态文件。",
        // 安装 serve 作为静态文件服务器。
        "RUN npm install -g serve",
        // 空行分隔安装 serve 和端口声明。
        "",
        // 端口声明说明。
        "# 声明容器对外服务端口。",
        // 声明目标服务端口。
        `EXPOSE ${asNumber(state.exposePort, 80)}`,
      );

      if (!cmdInstruction) {
        lines.push(
          // 空行分隔端口声明和启动命令。
          "",
          // 启动命令说明。
          "# 启动静态文件服务。",
          // 用 exec 形式 CMD 启动 serve。
          `CMD ["serve", "-s", "${outputDir}", "-l", "${asNumber(state.exposePort, 80)}"]`,
        );
      }
    }

    if (entrypointInstruction || cmdInstruction) {
      lines.push("", "# 覆写容器启动入口或默认命令。");
      if (entrypointInstruction) {
        lines.push(entrypointInstruction);
      }
      if (cmdInstruction) {
        lines.push(cmdInstruction);
      }
    }

    // 健康检查开启时追加 HEALTHCHECK 指令。
    if (state.enableHealthcheck) {
      // 输出 Docker 健康检查配置。
      lines.push(
        // 空行分隔主要配置和健康检查。
        "",
        // 健康检查说明。
        "# 容器健康检查，部署平台可据此判断实例是否可用。",
        // 使用 wget 请求本机端口和路径，失败时 exit 1。
        `HEALTHCHECK --interval=30s --timeout=3s --retries=3 CMD wget -qO- http://127.0.0.1:${asNumber(state.exposePort, 80)}${cleanString(state.healthcheckPath) || "/"} || exit 1`,
      );
    }

    // 合并所有行，去掉首尾空白，并保留文件末尾换行。
    return `${lines.join("\n").trim()}\n`;
  }

  // 返回给通用工作台使用的生成器接口。
  return {
    // 生成器唯一标识，用于顶部 Tab 选中状态。
    id: "dockerfile",
    // 顶部 Tab 展示名称。
    title: "Dockerfile",
    // 顶部 Tab 或辅助区域展示的简短说明。
    summary: "前端静态站点多阶段镜像",
    // 顶部 Tab 图标名称。
    icon: "Box",
    // 右侧代码块展示的语言标签。
    language: "Dockerfile",
    // 下载时使用的文件名。
    fileName: () => "Dockerfile",
    // 表单面板标题。
    panelTitle: () => "Dockerfile",
    // 表单面板说明，明确这是目标项目参考配置。
    panelLead: () => "为目标前端静态站点生成 Node 构建 + Nginx/Caddy 静态运行的参考 Dockerfile。",
    // 返回固定字段分组。
    getFieldGroups: () => groups,
    // Dockerfile 当前没有动态新增块，因此返回空数组。
    getBlocks: () => [],
    // 返回当前 Dockerfile 文本。
    generateConfig,
    // 生成面向目标项目的使用说明。
    generateUsage: () =>
      [
        // 第一步说明保存文件名。
        "1. 保存右侧内容为 Dockerfile。",
        // 第二步说明在目标项目里构建镜像。
        "2. 在目标项目根目录运行: docker build -t my-frontend .",
        // 第三步说明本地运行镜像时的端口映射。
        `3. 本地运行: docker run --rm -p 8080:${asNumber(state.exposePort, 80)} my-frontend。`,
        // 第四步说明浏览器访问路径。
        `4. 浏览器访问: http://localhost:8080${cleanString(state.healthcheckPath) || "/"}`,
      ].join("\n"),
    // 暴露该工具的参考配置规范(AI verify 上下文 + 人类查阅)。
    getReference: () => reference,
    // generate 模式需要表单 state key，而不是 Dockerfile 指令名。
    getAIContext: () => ({
      reference,
      expectedJson: {
        type: "object",
        keys: Object.keys(schema.state),
      },
      schema,
    }),
    // 按 schema 白名单把 AI 生成的 JSON 写回 state(generate 模式)。
    applyAIState: (json) => applyStateFromSchema(state, schema, json),
  };
}
