// 引入 Redis 表单 schema，字段、默认值和选项从这里读取。
import schema from "./redis/schema.json";
// 引入 Redis 配置参考，供 AI 校验和生成上下文使用。
import reference from "./redis/reference-doc.json";
// 引入 schema 加载器，把 JSON 数据转换成响应式表单状态。
import { applyStateFromSchema, createSchemaForm } from "./loader";
// 引入共享工具函数，负责数字兜底、字符串清理和多行解析。
import { asNumber, cleanString, parseLines } from "./shared";

// Redis 配置使用 yes/no，而表单里使用 boolean，这里统一做输出转换。
function yesNo(value) {
  return value ? "yes" : "no";
}

// Redis 某些指令需要双引号字符串，输出前转义反斜杠和双引号。
function quoted(value) {
  return `"${String(value ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// 大多数 Redis 指令都是“注释 + 指令值”的形态，集中处理可保持输出格式一致。
function pushDirective(lines, comment, directive, value) {
  if (value === "" || value === null || value === undefined) {
    return;
  }

  lines.push(`# ${comment}`, `${directive} ${value}`, "");
}

// 创建 Redis 参考配置生成器。
export function createRedisGenerator() {
  const { state, groups } = createSchemaForm(schema);

  // 根据当前表单 state 生成 redis.conf，并在每个常用指令前保留中文说明。
  function generateConfig() {
    const lines = [
      "# Generated by Config Gen",
      "",
    ];

    pushDirective(lines, "监听地址。仅本机访问可保持 127.0.0.1，容器或内网访问再按实际网络调整。", "bind", cleanString(state.bind));
    pushDirective(lines, "TCP 监听端口。设置为 0 可关闭普通 TCP 端口。", "port", asNumber(state.port, 6379));
    pushDirective(lines, "保护模式。公网或跨主机访问 Redis 前必须配合密码、ACL 和防火墙。", "protected-mode", yesNo(state.protectedMode));

    if (state.enableTls) {
      pushDirective(lines, "TLS 监听端口。需要 Redis 构建支持 TLS。", "tls-port", asNumber(state.tlsPort, 6380));
      pushDirective(lines, "TLS 服务端证书。", "tls-cert-file", cleanString(state.tlsCertFile));
      pushDirective(lines, "TLS 服务端私钥。", "tls-key-file", cleanString(state.tlsKeyFile));
      pushDirective(lines, "TLS CA 证书，用于校验客户端或上游证书。", "tls-ca-cert-file", cleanString(state.tlsCaCertFile));
    }

    if (state.enableAuth) {
      pushDirective(lines, "访问密码。生产环境请改成高强度随机值，并避免提交到公开仓库。", "requirepass", cleanString(state.requirepass));
    }
    pushDirective(lines, "ACL 用户文件。需要多用户权限控制时启用。", "aclfile", cleanString(state.aclfile));

    pushDirective(lines, "客户端空闲超时秒数，0 表示不主动断开。", "timeout", asNumber(state.timeout, 0));
    pushDirective(lines, "TCP keepalive 秒数，用于尽早发现异常断开的连接。", "tcp-keepalive", asNumber(state.tcpKeepalive, 300));
    pushDirective(lines, "逻辑数据库数量。集群模式只使用 DB 0。", "databases", asNumber(state.databases, 16));
    pushDirective(lines, "是否后台运行。Docker/容器环境通常保持 no。", "daemonize", yesNo(state.daemonize));
    pushDirective(lines, "进程监督方式。systemd 部署可设为 systemd。", "supervised", cleanString(state.supervised) || "no");

    pushDirective(lines, "数据文件目录。容器部署时建议挂载为持久化 volume。", "dir", cleanString(state.dir));
    pushDirective(lines, "RDB 快照文件名。", "dbfilename", cleanString(state.dbfilename));

    const saveRules = parseLines(state.saveRules);
    if (saveRules.length) {
      lines.push("# RDB 保存规则。格式为: save <秒> <变更次数>。");
      saveRules.forEach((rule) => lines.push(`save ${rule}`));
      lines.push("");
    } else {
      lines.push("# 关闭 RDB 快照。", "save \"\"", "");
    }

    pushDirective(lines, "是否启用 AOF。需要更稳的数据恢复时建议开启。", "appendonly", yesNo(state.appendonly));
    if (state.appendonly) {
      pushDirective(lines, "AOF 文件名。", "appendfilename", quoted(cleanString(state.appendfilename) || "appendonly.aof"));
      pushDirective(lines, "AOF 刷盘策略。everysec 通常是可靠性和性能的折中。", "appendfsync", cleanString(state.appendfsync) || "everysec");
    }

    pushDirective(lines, "最大内存。留空不生成；生产环境建议结合容器/主机内存明确设置。", "maxmemory", cleanString(state.maxmemory));
    pushDirective(lines, "内存达到上限后的淘汰策略。缓存型 Redis 常用 allkeys-lru。", "maxmemory-policy", cleanString(state.maxmemoryPolicy) || "noeviction");
    pushDirective(lines, "异步释放被淘汰 key，降低大对象释放造成的主线程阻塞。", "lazyfree-lazy-eviction", yesNo(state.lazyfreeLazyEviction));

    if (state.enableReplica) {
      pushDirective(lines, "将当前实例配置为副本，格式为: replicaof <master-host> <master-port>。", "replicaof", cleanString(state.replicaof));
      pushDirective(lines, "主节点密码。主节点启用 requirepass 时填写。", "masterauth", cleanString(state.masterauth));
    }

    pushDirective(lines, "日志级别。notice 适合大多数生产场景。", "loglevel", cleanString(state.loglevel) || "notice");
    pushDirective(lines, "日志文件。空字符串表示输出到 stdout，适合容器日志采集。", "logfile", quoted(cleanString(state.logfile)));
    pushDirective(lines, "慢查询阈值，单位微秒；10000 表示 10ms，负数表示关闭。", "slowlog-log-slower-than", asNumber(state.slowlogLogSlowerThan, 10000));
    pushDirective(lines, "慢查询日志保留条数。", "slowlog-max-len", asNumber(state.slowlogMaxLen, 128));
    pushDirective(lines, "键空间通知。示例 Ex 表示过期事件；留空不生成。", "notify-keyspace-events", cleanString(state.notifyKeyspaceEvents));

    const extraDirectives = parseLines(state.extraDirectives);
    if (extraDirectives.length) {
      lines.push("# 额外 Redis 指令，按当前输入原样追加。", ...extraDirectives, "");
    }

    return `${lines.join("\n").trim()}\n`;
  }

  return {
    id: "redis",
    title: "Redis",
    summary: "常用 redis.conf 参考",
    icon: "Database",
    language: "redis",
    fileName: () => "redis.conf",
    panelTitle: () => "Redis",
    panelLead: () => "为目标 Redis 单实例生成常用 redis.conf 参考配置，覆盖监听、安全、持久化、内存、日志和慢查询。",
    getFieldGroups: () => groups,
    getBlocks: () => [],
    generateConfig,
    generateUsage: () =>
      [
        "1. 保存右侧内容为 redis.conf，并替换 requirepass、bind、dir、证书路径等示例值。",
        "2. Docker 预览: docker run --rm -p 6379:6379 -v $PWD/redis.conf:/usr/local/etc/redis/redis.conf redis:7-alpine redis-server /usr/local/etc/redis/redis.conf",
        "3. 本机运行: redis-server ./redis.conf。",
        "4. 客户端测试: redis-cli -h 127.0.0.1 -p 6379 -a '<requirepass>' ping。",
        "5. 生产环境请限制 Redis 暴露范围，配合防火墙、安全组、ACL、强密码和持久化目录备份。",
      ].join("\n"),
    getReference: () => reference,
    getAIContext: () => ({
      reference,
      expectedJson: {
        type: "object",
        keys: Object.keys(schema.state),
      },
      schema,
    }),
    applyAIState: (json) => applyStateFromSchema(state, schema, json),
  };
}
