// 将表单输入转换为数字，并在空值或非法数字时使用兜底值。
export function asNumber(value, fallback = 0) {
  // 表单清空时会得到空字符串，统一视为没有填写。
  if (value === "" || value === null || value === undefined) {
    // 返回调用方提供的默认值，避免生成 NaN。
    return fallback;
  }

  // 使用 Number 保留端口、超时、重试次数等数字字段的语义。
  const next = Number(value);
  // 只有有限数字才进入配置，否则仍然回退到默认值。
  return Number.isFinite(next) ? next : fallback;
}

// 清理普通字符串输入，保证生成配置前后没有多余空白。
export function cleanString(value) {
  // 对 null/undefined 做空字符串兜底，再裁剪用户输入。
  return String(value || "").trim();
}

// 把逗号分隔的表单文本转换成配置需要的数组。
export function splitList(value) {
  // 如果调用方已经传入数组，只过滤掉空项即可。
  if (Array.isArray(value)) {
    // 保留用户提供的有效值，删除空字符串、null、undefined。
    return value.filter(Boolean);
  }

  // 普通文本按逗号切分，适合 ports、domains、headers 等输入。
  return String(value || "")
    // 以英文逗号作为当前 UI 的列表分隔符。
    .split(",")
    // 去掉每一项两侧空白，提升复制出来的配置质量。
    .map((item) => item.trim())
    // 删除空项，避免生成空数组元素。
    .filter(Boolean);
}

// 解析 key=value,key2=value2 形式的输入，用于 headers、environment、metadata。
export function parseKeyValuePairs(value) {
  // 先把输入统一转成字符串，便于链式处理。
  return String(value || "")
    // 多个键值对用逗号分隔。
    .split(",")
    // 清理每一项前后的空格。
    .map((item) => item.trim())
    // 跳过空项。
    .filter(Boolean)
    // 将每一项拆成 [key, value]。
    .map((item) => {
      // 只按第一个等号切分，允许 value 内部继续包含等号。
      const separatorIndex = item.indexOf("=");
      // 没写等号时保留 key，value 使用空字符串。
      if (separatorIndex === -1) {
        // 返回空值便于后续 YAML/TOML 渲染统一处理。
        return [item, ""];
      }

      // 正常 key=value 输入会进入这里。
      return [
        // 等号左侧是 key。
        item.slice(0, separatorIndex).trim(),
        // 等号右侧是 value。
        item.slice(separatorIndex + 1).trim(),
      ];
    })
    // 丢弃 key 为空的非法输入。
    .filter(([key]) => key);
}

// 将多行文本解析为非空行列表。
export function parseLines(value) {
  // 统一转成字符串，避免 null/undefined 抛错。
  return String(value || "")
    // 按换行符切分。
    .split("\n")
    // 清理每一行两侧空白。
    .map((item) => item.trim())
    // 只保留有内容的行。
    .filter(Boolean);
}

// 判断某个值在配置生成时是否应该被忽略。
export function isEmptyValue(value) {
  // undefined、null、空字符串、空数组都不应该输出到配置里。
  return (
    // 未定义值通常表示字段没有被启用。
    value === undefined ||
    // null 同样表示没有有效输入。
    value === null ||
    // 空字符串会生成无意义配置，直接跳过。
    value === "" ||
    // 空数组输出后没有实际配置意义，也跳过。
    (Array.isArray(value) && value.length === 0)
  );
}

// 将 JS 值转换为 TOML 字面量。
export function stringifyTomlValue(value) {
  // 数字保持裸值输出。
  if (typeof value === "number") {
    // 非有限数字不能写入 TOML，统一兜底为 0。
    return Number.isFinite(value) ? String(value) : "0";
  }

  // 布尔值按 TOML 的 true/false 输出。
  if (typeof value === "boolean") {
    // TOML 布尔值必须是小写。
    return value ? "true" : "false";
  }

  // 数组递归渲染内部元素。
  if (Array.isArray(value)) {
    // TOML 数组使用方括号，并用逗号分隔元素。
    return `[${value.map((item) => stringifyTomlValue(item)).join(", ")}]`;
  }

  // 对象用于渲染 TOML inline table，例如 { start = 1, end = 2 }。
  if (typeof value === "object") {
    // 先把对象条目转换为 key = value 的形式。
    const body = Object.entries(value)
      // inline table 里同样跳过空值。
      .filter(([, nestedValue]) => !isEmptyValue(nestedValue))
      // 嵌套值继续走 TOML 字面量转换，保证字符串会被引号包裹。
      .map(([key, nestedValue]) => `${key} = ${stringifyTomlValue(nestedValue)}`)
      // inline table 内部用逗号分隔。
      .join(", ");

    // 返回 TOML inline table。
    return `{ ${body} }`;
  }

  // 字符串需要转义反斜杠和双引号。
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// 根据配置键名查找对应注释。
export function resolveComment(comments, key) {
  // 优先使用精确键名注释。
  if (comments[key]) {
    // 找到精确注释时直接返回。
    return comments[key];
  }

  // 支持 requestHeaders.set.* 这类通配注释。
  const wildcardKey = Object.keys(comments).find(
    // 通配项必须以 .* 结尾，并匹配当前 key 的前缀。
    (candidate) =>
      candidate.endsWith(".*") && key.startsWith(candidate.slice(0, -1)),
  );

  // 找到通配注释则返回，否则返回空字符串。
  return wildcardKey ? comments[wildcardKey] : "";
}

// 渲染 TOML 根配置或 section 内配置项。
export function renderTomlEntries(entries, comments = {}) {
  // entries 是普通对象，按定义顺序输出。
  return Object.entries(entries)
    // 跳过未填写或未启用的字段。
    .filter(([, value]) => !isEmptyValue(value))
    // 每个字段可能渲染为“注释 + 配置行”两行。
    .flatMap(([key, value]) => {
      // 查找当前字段的中文说明。
      const comment = resolveComment(comments, key);
      // 生成真正的 TOML 配置行。
      const line = `${key} = ${stringifyTomlValue(value)}`;

      // 有注释时先输出注释，再输出配置；没有注释时只输出配置。
      return comment ? [`# ${comment}`, line] : [line];
    });
}

// 渲染完整 TOML 文件。
export function renderToml({ fileName, root, rootComments = {}, sections = [] }) {
  // 文件头说明来源和建议保存文件名。
  const lines = [
    // 标记配置由当前可视化工具生成。
    "# Generated by Config Gen",
    // 空行分隔头部和配置项。
    "",
    // 渲染根级配置。
    ...renderTomlEntries(root, rootComments),
  ];

  // 逐个渲染数组型 section，例如 [[proxies]]。
  sections.forEach((section) => {
    // section 前插入空行提升可读性。
    lines.push("");
    // section 级说明用于标识功能块。
    if (section.comment) {
      // TOML 注释以 # 开头。
      lines.push(`# ${section.comment}`);
    }
    // TOML 数组表语法，例如 [[proxies]]。
    lines.push(`[[${section.name}]]`);
    // 渲染当前 section 的所有配置项。
    lines.push(...renderTomlEntries(section.entries, section.entryComments));
  });

  // trim 去掉首尾多余空白，末尾补一个换行方便保存。
  return `${lines.join("\n").trim()}\n`;
}

// 生成单行注释文本，用于非 TOML 配置文件。
export function commentLine(text, prefix = "#") {
  // 默认使用 #，也可传入 // 等其他注释前缀。
  return `${prefix} ${text}`;
}

// 给多行文本统一增加缩进。
export function indent(lines, spaces = 2) {
  // 根据缩进空格数量生成前缀。
  const pad = " ".repeat(spaces);
  // 空行保持空行，非空行添加缩进。
  return lines.map((line) => (line ? `${pad}${line}` : line));
}

// 生成 YAML/JSON 兼容的双引号字符串。
export function q(value) {
  // JSON.stringify 会自动处理引号和反斜杠转义。
  return JSON.stringify(String(value ?? ""));
}

// 渲染 YAML 列表。
export function renderYamlList(items, indentSpaces = 2) {
  // 根据调用方指定层级生成缩进。
  const pad = " ".repeat(indentSpaces);
  // 每个列表项以前缀 "- " 输出。
  return items.map((item) => `${pad}- ${item}`);
}

// 渲染 YAML 键值对对象。
export function renderYamlKeyValuePairs(value, indentSpaces = 2) {
  // 根据 YAML 层级生成缩进。
  const pad = " ".repeat(indentSpaces);
  // 复用 key=value 解析器，把表单字符串转换为 YAML map。
  return parseKeyValuePairs(value).map(([key, pairValue]) => {
    // 没有 value 时输出空字符串，避免 YAML 解析成 null。
    if (!pairValue) {
      // 空值显式写成 ""。
      return `${pad}${key}: ""`;
    }
    // 有 value 时使用 q 保证字符串安全。
    return `${pad}${key}: ${q(pairValue)}`;
  });
}

// 生成前端运行期使用的唯一 ID。
export function createId(prefix) {
  // ID 由业务前缀、时间戳和随机片段组成，避免动态块 key 冲突。
  return `${prefix}-${Date.now().toString(36)}-${Math.random()
    // 随机数转换成 36 进制字符串。
    .toString(36)
    // 去掉开头的 0.，只保留随机主体。
    .slice(2, 8)}`;
}
